import React, { useState, useEffect } from 'react';
import { useForm } from '@inertiajs/react';

// INITIALLY GENERATED BY GEMINI
const WordleForm = () => {
    // 1. Inertia Form Setup
    const { data, setData, post, processing } = useForm({
        guess: '',
        attempts: [], // You can store previous attempts here
    });

    const [currentGuess, setCurrentGuess] = useState("");
    const rows = 6;
    const cols = 5;

    // 2. Custom Keyboard Logic
    const keys = [
        ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
        ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
        ['ENTER', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', 'DEL']
    ];

    const handleInput = (key) => {
        if (key === 'ENTER') {
            if (currentGuess.length === 5) {
                // Submit to your Laravel route
                post('/your-wordle-route');
            }
        } else if (key === 'DEL') {
            setCurrentGuess(prev => prev.slice(0, -1));
        } else if (currentGuess.length < 5 && /^[A-Z]$/.test(key)) {
            setCurrentGuess(prev => prev + key);
        }
    };

    // Listen for physical keyboard events (Desktop)
    useEffect(() => {
        const handleKeyDown = (e) => {
            const key = e.key.toUpperCase();
            if (key === 'BACKSPACE') handleInput('DEL');
            else handleInput(key);
        };
        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [currentGuess]);

    return (
        <div className="flex flex-col items-center justify-between min-h-screen text-black p-4">
            <h1 className="text-4xl font-bold mb-8">WORDLE</h1>

            {/* The Grid */}
            <div className="grid grid-rows-6 gap-2 mb-8">
                {[...Array(rows)].map((_, rowIndex) => (
                    <div key={rowIndex} className="flex gap-2">
                        {[...Array(cols)].map((_, colIndex) => {
                            // Logic to display current guess in the first empty row
                            const isCurrentRow = rowIndex === data.attempts.length;
                            const char = isCurrentRow ? currentGuess[colIndex] : "";

                            return (
                                <div key={colIndex} className="w-14 h-14 border-2 border-gray-700 flex items-center justify-center text-2xl font-bold uppercase">
                                    {char}
                                </div>
                            );
                        })}
                    </div>
                ))}
            </div>

            {/* The Keyboard */}
            <div className="w-full max-w-md">
                {keys.map((row, i) => (
                    <div key={i} className="flex justify-center gap-1 mb-2 touch-none">
                        {row.map((key) => (
                            <button
                                key={key}
                                type="button"
                                onClick={() => handleInput(key)}
                                className={`
                                    ${key.length > 1 ? 'px-4 text-xs' : 'flex-1 text-sm'}
                                    h-14 bg-gray-400 rounded font-bold hover:bg-gray-400 active:bg-gray-600 transition-colors
                                `}
                            >
                                {key}
                            </button>
                        ))}
                    </div>
                ))}
            </div>

            {/* Hidden Input to prevent mobile keyboard from popping up */}
            <input type="text" className="sr-only" readOnly />
        </div>
    );
};

export default WordleForm;
